/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2020.1.2                                                    */
/* Component Version:  V2020.1.1                                                    */
/* CAS Version:        V.04.00M0P01052021                                           */
/* SAS Version:        V.04.00M0P010521                                             */
/* Site Number:        70180938                                                     */
/* Host:               controller.sas-cas-server-default.base.svc.cluster.local     */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       5d79a6e8-28ae-405a-871b-ed57cde2bffa                         */
/* Node GUID:          9d1ef204-a525-4e69-bee4-5822551f50f0                         */
/* Node Id:            9AVB56RG138BYEX3DURBJXWC0                                    */
/* Algorithm:          Forest                                                       */
/* Generated by:       scnkuj                                                       */
/* Date:               13JAN2021:06:49:40                                           */
/*----------------------------------------------------------------------------------*/
package MS_9d1ef204a5254e69bee45822551f50f0_13JAN2021064940063 / overwrite=yes;
   dcl package score _9AVB56RG138BYEX3DURBJXWC0();
   dcl double "P_BAD1" having label n'Predicted: BAD=1';
   dcl double "P_BAD0" having label n'Predicted: BAD=0';
   dcl nchar(32) "I_BAD" having label n'Into: BAD';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   dcl double EM_EVENTPROBABILITY;
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double EM_PROBABILITY;
   varlist allvars [_all_];
 
    
   method init();
      _9AVB56RG138BYEX3DURBJXWC0.setvars(allvars);
      _9AVB56RG138BYEX3DURBJXWC0.setkey(n'D44CA451EA46EB9076E1DD40F8C9ED098DE3ABE5');
      _9AVB56RG138BYEX3DURBJXWC0.setOption('_destroyFirstInstLast_', 0);
   end;
    
   method post_9AVB56RG138BYEX3DURBJXWC0();
      dcl double _P_;
       
      if "P_BAD0" = . then "P_BAD0" = 0.7890939597;
      if "P_BAD1" = . then "P_BAD1" = 0.2109060403;
      if MISSING("I_BAD") then do ;
      _P_ = 0.0;
      if "P_BAD1" > _P_ then do ;
      _P_ = "P_BAD1";
      "I_BAD" = '           1';
      end;
      if "P_BAD0" > _P_ then do ;
      _P_ = "P_BAD0";
      "I_BAD" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_BAD1";
      EM_CLASSIFICATION = "I_BAD";
      EM_PROBABILITY = MAX("P_BAD1", "P_BAD0");
    
   end;
    
 
   method score(
      double "CLAGE",
      double "CLNO",
      double "DEBTINC",
      double "DELINQ",
      double "DEROG",
      char(7) "JOB",
      double "LOAN",
      double "MORTDUE",
      double "NINQ",
      char(7) "REASON",
      double "VALUE",
      double "YOJ",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_BAD",
      IN_OUT double "P_BAD0",
      IN_OUT double "P_BAD1",
      IN_OUT double "_P_",
      IN_OUT char(4) "_WARN_"
   );
      this."CLAGE"= "CLAGE";
      this."CLNO"= "CLNO";
      this."DEBTINC"= "DEBTINC";
      this."DELINQ"= "DELINQ";
      this."DEROG"= "DEROG";
      this."JOB"= "JOB";
      this."LOAN"= "LOAN";
      this."MORTDUE"= "MORTDUE";
      this."NINQ"= "NINQ";
      this."REASON"= "REASON";
      this."VALUE"= "VALUE";
      this."YOJ"= "YOJ";
 
      _9AVB56RG138BYEX3DURBJXWC0.scoreRecord();
      post_9AVB56RG138BYEX3DURBJXWC0();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_BAD"= this."I_BAD";
      "P_BAD0"= this."P_BAD0";
      "P_BAD1"= this."P_BAD1";
      "_P_"= this."_P_";
      "_WARN_"= this."_WARN_";
   end;
 
 
   method predictedscore(
      double "CLAGE",
      double "CLNO",
      double "DEBTINC",
      double "DELINQ",
      double "DEROG",
      char(7) "JOB",
      double "LOAN",
      double "MORTDUE",
      double "NINQ",
      char(7) "REASON",
      double "VALUE",
      double "YOJ",
      IN_OUT char(12) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(32) "I_BAD",
      IN_OUT double "P_BAD0",
      IN_OUT double "P_BAD1",
      IN_OUT char(4) "_WARN_"
   );
      this."CLAGE"= "CLAGE";
      this."CLNO"= "CLNO";
      this."DEBTINC"= "DEBTINC";
      this."DELINQ"= "DELINQ";
      this."DEROG"= "DEROG";
      this."JOB"= "JOB";
      this."LOAN"= "LOAN";
      this."MORTDUE"= "MORTDUE";
      this."NINQ"= "NINQ";
      this."REASON"= "REASON";
      this."VALUE"= "VALUE";
      this."YOJ"= "YOJ";
 
      _9AVB56RG138BYEX3DURBJXWC0.scoreRecord();
      post_9AVB56RG138BYEX3DURBJXWC0();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_BAD"= this."I_BAD";
      "P_BAD0"= this."P_BAD0";
      "P_BAD1"= this."P_BAD1";
      "_WARN_"= this."_WARN_";
   end;
 
endpackage;
